name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  testing-8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: xdebug
          extensions: sqlite3, pdo_sqlite
          tools: composer, phpunit
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php8-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer
        run: composer install
      - name: Run Tests
        run: composer run test-coverage
  testing-74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug
          extensions: sqlite3, pdo_sqlite
          tools: composer, phpunit
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php7-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer
        run: composer install
      - name: Run Tests
        run: composer run test-coverage
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: php-cs-fixer
      - name: Run Lint Check
        run: php-cs-fixer fix --dry-run -vv --diff --config=.php_cs.dist.php
  phan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phan
      - name: Run Static Analysis
        run: phan --progress-bar -o phan_analysis.txt
